'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import {MantineProvider, AppShell, Group, Burger, Skeleton, NavLink} from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import {useDisclosure} from "@mantine/hooks";
import Link from "next/link";
import '@mantine/dates/styles.css';
import { IconChevronRight } from "@tabler/icons-react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const [opened, { toggle }] = useDisclosure();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <MantineProvider defaultColorScheme="light">
          <Notifications />

          <AppShell
              header={{ height: 60 }}
              navbar={{ width: 300, breakpoint: 'sm', collapsed: { mobile: !opened } }}
              padding="md"
          >
              <AppShell.Header>
                  <Group h="100%" px="md">
                      <Burger opened={opened} onClick={toggle} hiddenFrom="sm" size="sm" />
                      {/*<MantineLogo size={30} />*/}
                  </Group>
              </AppShell.Header>
              <AppShell.Navbar p="md">
                      <NavLink
                          component={Link}
                          href="/debit-upload"
                          label="Document Upload"
                          rightSection={
                              <IconChevronRight size={12} stroke={1.5} className="mantine-rotate-rtl" />
                          }
                      />
                      <NavLink
                          component={Link}
                          href="/receipts"
                          label="Receipts"
                          rightSection={
                              <IconChevronRight size={12} stroke={1.5} className="mantine-rotate-rtl" />
                          }
                      />
                      {/* add more links as needed */}
              </AppShell.Navbar>
              <AppShell.Main>{children}</AppShell.Main>
          </AppShell>
      </MantineProvider>
      </body>
    </html>
  );
}
